#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_HOST=axel@raspberrypi
readonly TARGET_PATH=/home/axel/clicks/clicks
readonly TARGET_ARCH=aarch64-unknown-linux-gnu
readonly SOURCE_PATH=./target/${TARGET_ARCH}/release/clicks-rust

export PKG_CONFIG_SYSROOT_DIR=/home/axel/git/raspberrypi
export RUSTFLAGS='-L /home/axel/git/raspberrypi/usr/lib/aarch64-linux-gnu'


cargo build --release --target=${TARGET_ARCH} --features i2c-ui
rsync ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}
ssh -t ${TARGET_HOST} ${TARGET_PATH}
